From Coq Require Import Program.Subset.
From Coq Require Import Program.Utils.
From Coq Require Import Program.Syntax.
From Coq Require Import Program.Wf.
From Coq Require Import Program.Combinators.
From Coq Require Import Program.Tactics.
From Coq Require Import Program.Equality.
From Coq Require Import Program.Program.
From Coq Require Import Program.Basics.
From Coq Require Import Bool.Bvector.
From Coq Require Import Bool.Zerob.
From Coq Require Import Bool.Sumbool.
From Coq Require Import Bool.DecBool.
From Coq Require Import Bool.BoolOrder.
From Coq Require Import Bool.BoolEq.
From Coq Require Import Bool.Bool.
From Coq Require Import Bool.IfProp.
From Coq Require Import derive.Derive.
From Coq Require Import Setoids.Setoid.
From Coq Require Import Strings.PrimStringAxioms.
From Coq Require Import Strings.Byte.
From Coq Require Import Strings.PString.
From Coq Require Import Strings.Ascii.
From Coq Require Import Strings.PrimString.
From Coq Require Import Strings.BinaryString.
From Coq Require Import Strings.HexString.
From Coq Require Import Strings.OctalString.
From Coq Require Import Strings.String.
From Coq Require Import nsatz.Nsatz.
From Coq Require Import nsatz.NsatzTactic.
From Coq Require Import rtauto.Rtauto.
From Coq Require Import rtauto.Bintree.
From Coq Require Import ssrmatching.ssrmatching.
From Coq Require Import MSets.MSetAVL.
From Coq Require Import MSets.MSetGenTree.
From Coq Require Import MSets.MSetWeakList.
From Coq Require Import MSets.MSetFacts.
From Coq Require Import MSets.MSetPositive.
From Coq Require Import MSets.MSetToFiniteSet.
From Coq Require Import MSets.MSetDecide.
From Coq Require Import MSets.MSetProperties.
From Coq Require Import MSets.MSetInterface.
From Coq Require Import MSets.MSetList.
From Coq Require Import MSets.MSetEqProperties.
From Coq Require Import MSets.MSets.
From Coq Require Import MSets.MSetRBT.
From Coq Require Import Arith.Compare.
From Coq Require Import Arith.Cantor.
From Coq Require Import Arith.EqNat.
From Coq Require Import Arith.Factorial.
From Coq Require Import Arith.Arith.
From Coq Require Import Arith.PeanoNat.
From Coq Require Import Arith.Arith_base.
From Coq Require Import Arith.Wf_nat.
From Coq Require Import Arith.Compare_dec.
From Coq Require Import Arith.Between.
From Coq Require Import Arith.Bool_nat.
From Coq Require Import Arith.Euclid.
From Coq Require Import Arith.Peano_dec.
From Coq Require Import ssr.ssrclasses.
From Coq Require Import ssr.ssrsetoid.
From Coq Require Import ssr.ssreflect.
From Coq Require Import ssr.ssrfun.
From Coq Require Import ssr.ssrunder.
From Coq Require Import ssr.ssrbool.
From Coq Require Import Numbers.DecimalZ.
From Coq Require Import Numbers.HexadecimalString.
From Coq Require Import Numbers.HexadecimalQ.
From Coq Require Import Numbers.NumPrelude.
From Coq Require Import Numbers.NaryFunctions.
From Coq Require Import Numbers.DecimalR.
From Coq Require Import Numbers.DecimalFacts.
From Coq Require Import Numbers.AltBinNotations.
From Coq Require Import Numbers.HexadecimalFacts.
From Coq Require Import Numbers.DecimalString.
From Coq Require Import Numbers.DecimalPos.
From Coq Require Import Numbers.HexadecimalNat.
From Coq Require Import Numbers.HexadecimalPos.
From Coq Require Import Numbers.DecimalNat.
From Coq Require Import Numbers.HexadecimalR.
From Coq Require Import Numbers.DecimalQ.
From Coq Require Import Numbers.DecimalN.
From Coq Require Import Numbers.HexadecimalN.
From Coq Require Import Numbers.HexadecimalZ.
From Coq Require Import Numbers.BinNums.
From Coq Require Import Numbers.NatInt.NZDomain.
From Coq Require Import Numbers.NatInt.NZBase.
From Coq Require Import Numbers.NatInt.NZMulOrder.
From Coq Require Import Numbers.NatInt.NZAxioms.
From Coq Require Import Numbers.NatInt.NZBits.
From Coq Require Import Numbers.NatInt.NZOrder.
From Coq Require Import Numbers.NatInt.NZDiv.
From Coq Require Import Numbers.NatInt.NZProperties.
From Coq Require Import Numbers.NatInt.NZAddOrder.
From Coq Require Import Numbers.NatInt.NZParity.
From Coq Require Import Numbers.NatInt.NZMul.
From Coq Require Import Numbers.NatInt.NZSqrt.
From Coq Require Import Numbers.NatInt.NZPow.
From Coq Require Import Numbers.NatInt.NZGcd.
From Coq Require Import Numbers.NatInt.NZAdd.
From Coq Require Import Numbers.NatInt.NZLog.
From Coq Require Import Numbers.Cyclic.Abstract.CyclicAxioms.
From Coq Require Import Numbers.Cyclic.Abstract.DoubleType.
From Coq Require Import Numbers.Cyclic.Abstract.NZCyclic.
From Coq Require Import Numbers.Cyclic.Abstract.CarryType.
From Coq Require Import Numbers.Cyclic.Int63.Uint63.
From Coq Require Import Numbers.Cyclic.Int63.PrimInt63.
From Coq Require Import Numbers.Cyclic.Int63.Cyclic63.
From Coq Require Import Numbers.Cyclic.Int63.Sint63.
From Coq Require Import Numbers.Cyclic.Int63.Ring63.
From Coq Require Import Numbers.Integer.Abstract.ZProperties.
From Coq Require Import Numbers.Integer.Abstract.ZAxioms.
From Coq Require Import Numbers.Integer.Abstract.ZAdd.
From Coq Require Import Numbers.Integer.Abstract.ZParity.
From Coq Require Import Numbers.Integer.Abstract.ZBits.
From Coq Require Import Numbers.Integer.Abstract.ZMulOrder.
From Coq Require Import Numbers.Integer.Abstract.ZBase.
From Coq Require Import Numbers.Integer.Abstract.ZDivEucl.
From Coq Require Import Numbers.Integer.Abstract.ZPow.
From Coq Require Import Numbers.Integer.Abstract.ZMaxMin.
From Coq Require Import Numbers.Integer.Abstract.ZDivTrunc.
From Coq Require Import Numbers.Integer.Abstract.ZMul.
From Coq Require Import Numbers.Integer.Abstract.ZAddOrder.
From Coq Require Import Numbers.Integer.Abstract.ZSgnAbs.
From Coq Require Import Numbers.Integer.Abstract.ZGcd.
From Coq Require Import Numbers.Integer.Abstract.ZLcm.
From Coq Require Import Numbers.Integer.Abstract.ZDivFloor.
From Coq Require Import Numbers.Integer.Abstract.ZLt.
From Coq Require Import Numbers.Integer.NatPairs.ZNatPairs.
From Coq Require Import Numbers.Integer.Binary.ZBinary.
From Coq Require Import Numbers.Natural.Abstract.NAddOrder.
From Coq Require Import Numbers.Natural.Abstract.NLog.
From Coq Require Import Numbers.Natural.Abstract.NMaxMin.
From Coq Require Import Numbers.Natural.Abstract.NDiv.
From Coq Require Import Numbers.Natural.Abstract.NIso.
From Coq Require Import Numbers.Natural.Abstract.NLcm0.
From Coq Require Import Numbers.Natural.Abstract.NMulOrder.
From Coq Require Import Numbers.Natural.Abstract.NAdd.
From Coq Require Import Numbers.Natural.Abstract.NBits.
From Coq Require Import Numbers.Natural.Abstract.NDiv0.
From Coq Require Import Numbers.Natural.Abstract.NOrder.
From Coq Require Import Numbers.Natural.Abstract.NParity.
From Coq Require Import Numbers.Natural.Abstract.NStrongRec.
From Coq Require Import Numbers.Natural.Abstract.NGcd.
From Coq Require Import Numbers.Natural.Abstract.NAxioms.
From Coq Require Import Numbers.Natural.Abstract.NDefOps.
From Coq Require Import Numbers.Natural.Abstract.NLcm.
From Coq Require Import Numbers.Natural.Abstract.NSqrt.
From Coq Require Import Numbers.Natural.Abstract.NProperties.
From Coq Require Import Numbers.Natural.Abstract.NBase.
From Coq Require Import Numbers.Natural.Abstract.NSub.
From Coq Require Import Numbers.Natural.Abstract.NPow.
From Coq Require Import Numbers.Natural.Binary.NBinary.
From Coq Require Import Array.PArray.
From Coq Require Import Compat.Coq818.
From Coq Require Import Compat.Coq820.
From Coq Require Import Compat.AdmitAxiom.
From Coq Require Import Compat.Coq819.
From Coq Require Import Structures.OrdersTac.
From Coq Require Import Structures.Orders.
From Coq Require Import Structures.EqualitiesFacts.
From Coq Require Import Structures.OrdersEx.
From Coq Require Import Structures.OrdersLists.
From Coq Require Import Structures.OrderedTypeEx.
From Coq Require Import Structures.DecidableType.
From Coq Require Import Structures.DecidableTypeEx.
From Coq Require Import Structures.OrdersAlt.
From Coq Require Import Structures.OrderedType.
From Coq Require Import Structures.OrderedTypeAlt.
From Coq Require Import Structures.OrdersFacts.
From Coq Require Import Structures.GenericMinMax.
From Coq Require Import Structures.Equalities.
From Coq Require Import NArith.Ngcd_def.
From Coq Require Import NArith.Nsqrt_def.
From Coq Require Import NArith.BinNatDef.
From Coq Require Import NArith.BinNat.
From Coq Require Import NArith.Ndec.
From Coq Require Import NArith.Nnat.
From Coq Require Import NArith.NArith.
From Coq Require Import NArith.Ndiv_def.
From Coq Require Import Logic.SetIsType.
From Coq Require Import Logic.ExtensionalityFacts.
From Coq Require Import Logic.ClassicalEpsilon.
From Coq Require Import Logic.ExtensionalFunctionRepresentative.
From Coq Require Import Logic.ClassicalUniqueChoice.
From Coq Require Import Logic.Diaconescu.
From Coq Require Import Logic.FinFun.
From Coq Require Import Logic.StrictProp.
From Coq Require Import Logic.PropExtensionalityFacts.
From Coq Require Import Logic.Classical.
From Coq Require Import Logic.Hurkens.
From Coq Require Import Logic.ProofIrrelevance.
From Coq Require Import Logic.Adjointification.
From Coq Require Import Logic.ClassicalDescription.
From Coq Require Import Logic.Classical_Prop.
From Coq Require Import Logic.SetoidChoice.
From Coq Require Import Logic.Eqdep.
From Coq Require Import Logic.JMeq.
From Coq Require Import Logic.Eqdep_dec.
From Coq Require Import Logic.ClassicalFacts.
From Coq Require Import Logic.RelationalChoice.
From Coq Require Import Logic.ChoiceFacts.
From Coq Require Import Logic.Classical_Pred_Type.
From Coq Require Import Logic.ClassicalChoice.
From Coq Require Import Logic.Description.
From Coq Require Import Logic.PropExtensionality.
From Coq Require Import Logic.PropFacts.
From Coq Require Import Logic.IndefiniteDescription.
From Coq Require Import Logic.ConstructiveEpsilon.
From Coq Require Import Logic.WeakFan.
From Coq Require Import Logic.HLevels.
From Coq Require Import Logic.Berardi.
From Coq Require Import Logic.ProofIrrelevanceFacts.
From Coq Require Import Logic.Decidable.
From Coq Require Import Logic.EqdepFacts.
From Coq Require Import Logic.FunctionalExtensionality.
From Coq Require Import Logic.WKL.
From Coq Require Import Logic.Epsilon.
From Coq Require Import Relations.Relation_Operators.
From Coq Require Import Relations.Relations.
From Coq Require Import Relations.Operators_Properties.
From Coq Require Import Relations.Relation_Definitions.
From Coq Require Import omega.PreOmega.
From Coq Require Import omega.OmegaLemmas.
From Coq Require Import micromega.RingMicromega.
From Coq Require Import micromega.Fourier_util.
From Coq Require Import micromega.ZifyPow.
From Coq Require Import micromega.Refl.
From Coq Require Import micromega.QMicromega.
From Coq Require Import micromega.ZMicromega.
From Coq Require Import micromega.MExtraction.
From Coq Require Import micromega.ZifyInst.
From Coq Require Import micromega.Ztac.
From Coq Require Import micromega.DeclConstant.
From Coq Require Import micromega.Env.
From Coq Require Import micromega.Psatz.
From Coq Require Import micromega.Zify.
From Coq Require Import micromega.EnvRing.
From Coq Require Import micromega.Tauto.
From Coq Require Import micromega.ZifyClasses.
From Coq Require Import micromega.ZifyComparison.
From Coq Require Import micromega.OrderedRing.
From Coq Require Import micromega.ZifyN.
From Coq Require Import micromega.Lqa.
From Coq Require Import micromega.Lia.
From Coq Require Import micromega.ZifyUint63.
From Coq Require Import micromega.VarMap.
From Coq Require Import micromega.ZifySint63.
From Coq Require Import micromega.RMicromega.
From Coq Require Import micromega.Lra.
From Coq Require Import micromega.ZArith_hints.
From Coq Require Import micromega.ZCoeff.
From Coq Require Import micromega.ZifyBool.
From Coq Require Import micromega.Fourier.
From Coq Require Import micromega.ZifyNat.
From Coq Require Import Vectors.VectorSpec.
From Coq Require Import Vectors.VectorDef.
From Coq Require Import Vectors.Fin.
From Coq Require Import Vectors.VectorEq.
From Coq Require Import Vectors.Vector.
From Coq Require Import btauto.Reflect.
From Coq Require Import btauto.Btauto.
From Coq Require Import btauto.Algebra.
From Coq Require Import Unicode.Utf8_core.
From Coq Require Import Unicode.Utf8.
From Coq Require Import Init.Datatypes.
From Coq Require Import Init.Byte.
From Coq Require Import Init.Specif.
From Coq Require Import Init.Wf.
From Coq Require Import Init.Ltac.
From Coq Require Import Init.Tauto.
From Coq Require Import Init.Tactics.
From Coq Require Import Init.Peano.
From Coq Require Import Init.Number.
From Coq Require Import Init.Notations.
From Coq Require Import Init.Prelude.
From Coq Require Import Init.Hexadecimal.
From Coq Require Import Init.Decimal.
From Coq Require Import Init.Nat.
From Coq Require Import Init.Logic.
From Coq Require Import Floats.Floats.
From Coq Require Import Floats.FloatOps.
From Coq Require Import Floats.FloatAxioms.
From Coq Require Import Floats.PrimFloat.
From Coq Require Import Floats.FloatLemmas.
From Coq Require Import Floats.FloatClass.
From Coq Require Import Floats.SpecFloat.
From Coq Require Import Reals.ClassicalDedekindReals.
From Coq Require Import Reals.Binomial.
From Coq Require Import Reals.Cos_plus.
From Coq Require Import Reals.Machin.
From Coq Require Import Reals.Ranalysis1.
From Coq Require Import Reals.Rbasic_fun.
From Coq Require Import Reals.Rsqrt_def.
From Coq Require Import Reals.RiemannInt_SF.
From Coq Require Import Reals.Rpow_def.
From Coq Require Import Reals.SeqSeries.
From Coq Require Import Reals.AltSeries.
From Coq Require Import Reals.Rminmax.
From Coq Require Import Reals.Raxioms.
From Coq Require Import Reals.DiscrR.
From Coq Require Import Reals.Rtrigo_fun.
From Coq Require Import Reals.Rtrigo_calc.
From Coq Require Import Reals.Cauchy_prod.
From Coq Require Import Reals.Rsigma.
From Coq Require Import Reals.ArithProp.
From Coq Require Import Reals.SplitAbsolu.
From Coq Require Import Reals.Ranalysis4.
From Coq Require Import Reals.Rfunctions.
From Coq Require Import Reals.Reals.
From Coq Require Import Reals.Rtrigo_alt.
From Coq Require Import Reals.MVT.
From Coq Require Import Reals.Rseries.
From Coq Require Import Reals.Rdefinitions.
From Coq Require Import Reals.Rcomplete.
From Coq Require Import Reals.Rderiv.
From Coq Require Import Reals.Rbase.
From Coq Require Import Reals.Ranalysis_reg.
From Coq Require Import Reals.Ranalysis3.
From Coq Require Import Reals.RIneq.
From Coq Require Import Reals.Ranalysis2.
From Coq Require Import Reals.Rtrigo_def.
From Coq Require Import Reals.Rtrigo_facts.
From Coq Require Import Reals.Rtrigo_reg.
From Coq Require Import Reals.PSeries_reg.
From Coq Require Import Reals.PartSum.
From Coq Require Import Reals.R_Ifp.
From Coq Require Import Reals.NewtonInt.
From Coq Require Import Reals.ClassicalConstructiveReals.
From Coq Require Import Reals.Rlimit.
From Coq Require Import Reals.Rtopology.
From Coq Require Import Reals.ROrderedType.
From Coq Require Import Reals.RList.
From Coq Require Import Reals.R_sqrt.
From Coq Require Import Reals.Sqrt_reg.
From Coq Require Import Reals.Ratan.
From Coq Require Import Reals.SeqProp.
From Coq Require Import Reals.Cos_rel.
From Coq Require Import Reals.Exp_prop.
From Coq Require Import Reals.Ranalysis5.
From Coq Require Import Reals.Rprod.
From Coq Require Import Reals.Rregisternames.
From Coq Require Import Reals.Rtrigo.
From Coq Require Import Reals.Rpower.
From Coq Require Import Reals.Ranalysis.
From Coq Require Import Reals.Rtrigo1.
From Coq Require Import Reals.SplitRmult.
From Coq Require Import Reals.Rgeom.
From Coq Require Import Reals.Alembert.
From Coq Require Import Reals.RiemannInt.
From Coq Require Import Reals.Integration.
From Coq Require Import Reals.Runcountable.
From Coq Require Import Reals.Rlogic.
From Coq Require Import Reals.R_sqr.
From Coq Require Import Reals.Cauchy.QExtra.
From Coq Require Import Reals.Cauchy.ConstructiveCauchyReals.
From Coq Require Import Reals.Cauchy.ConstructiveRcomplete.
From Coq Require Import Reals.Cauchy.ConstructiveExtra.
From Coq Require Import Reals.Cauchy.ConstructiveCauchyAbs.
From Coq Require Import Reals.Cauchy.ConstructiveCauchyRealsMult.
From Coq Require Import Reals.Cauchy.PosExtra.
From Coq Require Import Reals.Abstract.ConstructiveLimits.
From Coq Require Import Reals.Abstract.ConstructiveLUB.
From Coq Require Import Reals.Abstract.ConstructiveRealsMorphisms.
From Coq Require Import Reals.Abstract.ConstructiveSum.
From Coq Require Import Reals.Abstract.ConstructiveMinMax.
From Coq Require Import Reals.Abstract.ConstructivePower.
From Coq Require Import Reals.Abstract.ConstructiveReals.
From Coq Require Import Reals.Abstract.ConstructiveAbs.
From Coq Require Import Lists.SetoidPermutation.
From Coq Require Import Lists.ListDec.
From Coq Require Import Lists.StreamMemo.
From Coq Require Import Lists.List.
From Coq Require Import Lists.SetoidList.
From Coq Require Import Lists.ListTactics.
From Coq Require Import Lists.Streams.
From Coq Require Import Lists.ListSet.
From Coq Require Import Classes.SetoidDec.
From Coq Require Import Classes.Init.
From Coq Require Import Classes.DecidableClass.
From Coq Require Import Classes.Morphisms.
From Coq Require Import Classes.Equivalence.
From Coq Require Import Classes.Morphisms_Prop.
From Coq Require Import Classes.CMorphisms.
From Coq Require Import Classes.CEquivalence.
From Coq Require Import Classes.RelationPairs.
From Coq Require Import Classes.RelationClasses.
From Coq Require Import Classes.SetoidTactics.
From Coq Require Import Classes.CRelationClasses.
From Coq Require Import Classes.SetoidClass.
From Coq Require Import Classes.Morphisms_Relations.
From Coq Require Import Classes.EquivDec.
From Coq Require Import Sorting.Heap.
From Coq Require Import Sorting.PermutSetoid.
From Coq Require Import Sorting.PermutEq.
From Coq Require Import Sorting.CPermutation.
From Coq Require Import Sorting.Sorted.
From Coq Require Import Sorting.Sorting.
From Coq Require Import Sorting.Permutation.
From Coq Require Import Sorting.Mergesort.
From Coq Require Import Wellfounded.Well_Ordering.
From Coq Require Import Wellfounded.Disjoint_Union.
From Coq Require Import Wellfounded.Union.
From Coq Require Import Wellfounded.Lexicographic_Product.
From Coq Require Import Wellfounded.Transitive_Closure.
From Coq Require Import Wellfounded.Lexicographic_Exponentiation.
From Coq Require Import Wellfounded.Inclusion.
From Coq Require Import Wellfounded.Wellfounded.
From Coq Require Import Wellfounded.Inverse_Image.
From Coq Require Import extraction.ExtrHaskellNatInteger.
From Coq Require Import extraction.ExtrOcamlNativeString.
From Coq Require Import extraction.ExtrOCamlFloats.
From Coq Require Import extraction.ExtrHaskellZInteger.
From Coq Require Import extraction.ExtrOCamlPArray.
From Coq Require Import extraction.Extraction.
From Coq Require Import extraction.ExtrHaskellString.
From Coq Require Import extraction.ExtrOcamlZInt.
From Coq Require Import extraction.ExtrOcamlZBigInt.
From Coq Require Import extraction.ExtrHaskellZNum.
From Coq Require Import extraction.ExtrOcamlChar.
From Coq Require Import extraction.ExtrHaskellBasic.
From Coq Require Import extraction.ExtrHaskellZInt.
From Coq Require Import extraction.ExtrOCamlInt63.
From Coq Require Import extraction.ExtrOCamlPString.
From Coq Require Import extraction.ExtrOcamlIntConv.
From Coq Require Import extraction.ExtrOcamlString.
From Coq Require Import extraction.ExtrOcamlNatInt.
From Coq Require Import extraction.ExtrOcamlBasic.
From Coq Require Import extraction.ExtrHaskellNatInt.
From Coq Require Import extraction.ExtrOcamlNatBigInt.
From Coq Require Import extraction.ExtrHaskellNatNum.
From Coq Require Import PArith.BinPos.
From Coq Require Import PArith.POrderedType.
From Coq Require Import PArith.Pnat.
From Coq Require Import PArith.BinPosDef.
From Coq Require Import PArith.PArith.
From Coq Require Import Sets.Classical_sets.
From Coq Require Import Sets.Uniset.
From Coq Require Import Sets.Relations_2.
From Coq Require Import Sets.Partial_Order.
From Coq Require Import Sets.Ensembles.
From Coq Require Import Sets.Constructive_sets.
From Coq Require Import Sets.Permut.
From Coq Require Import Sets.Relations_1.
From Coq Require Import Sets.Multiset.
From Coq Require Import Sets.Relations_3_facts.
From Coq Require Import Sets.Finite_sets.
From Coq Require Import Sets.Image.
From Coq Require Import Sets.Finite_sets_facts.
From Coq Require Import Sets.Cpo.
From Coq Require Import Sets.Relations_2_facts.
From Coq Require Import Sets.Infinite_sets.
From Coq Require Import Sets.Powerset_Classical_facts.
From Coq Require Import Sets.Integers.
From Coq Require Import Sets.Relations_1_facts.
From Coq Require Import Sets.Powerset_facts.
From Coq Require Import Sets.Relations_3.
From Coq Require Import Sets.Powerset.
From Coq Require Import FSets.FSetDecide.
From Coq Require Import FSets.FMapPositive.
From Coq Require Import FSets.FSetProperties.
From Coq Require Import FSets.FMapWeakList.
From Coq Require Import FSets.FSetFacts.
From Coq Require Import FSets.FMapAVL.
From Coq Require Import FSets.FMaps.
From Coq Require Import FSets.FMapInterface.
From Coq Require Import FSets.FSetEqProperties.
From Coq Require Import FSets.FSetToFiniteSet.
From Coq Require Import FSets.FSetBridge.
From Coq Require Import FSets.FSetCompat.
From Coq Require Import FSets.FSetInterface.
From Coq Require Import FSets.FSetAVL.
From Coq Require Import FSets.FSets.
From Coq Require Import FSets.FSetWeakList.
From Coq Require Import FSets.FMapList.
From Coq Require Import FSets.FSetPositive.
From Coq Require Import FSets.FMapFacts.
From Coq Require Import FSets.FSetList.
From Coq Require Import FSets.FMapFullAVL.
From Coq Require Import QArith.QOrderedType.
From Coq Require Import QArith.Qcanon.
From Coq Require Import QArith.Qreals.
From Coq Require Import QArith.Qreduction.
From Coq Require Import QArith.Qround.
From Coq Require Import QArith.Qabs.
From Coq Require Import QArith.QArith_base.
From Coq Require Import QArith.Qfield.
From Coq Require Import QArith.Qcabs.
From Coq Require Import QArith.QArith.
From Coq Require Import QArith.Qpower.
From Coq Require Import QArith.Qminmax.
From Coq Require Import QArith.Qring.
From Coq Require Import setoid_ring.Rings_Z.
From Coq Require Import setoid_ring.Field.
From Coq Require Import setoid_ring.NArithRing.
From Coq Require Import setoid_ring.Ring_polynom.
From Coq Require Import setoid_ring.Ncring_initial.
From Coq Require Import setoid_ring.Integral_domain.
From Coq Require Import setoid_ring.Cring.
From Coq Require Import setoid_ring.Ncring_polynom.
From Coq Require Import setoid_ring.Ncring.
From Coq Require Import setoid_ring.Algebra_syntax.
From Coq Require Import setoid_ring.Rings_Q.
From Coq Require Import setoid_ring.Field_tac.
From Coq Require Import setoid_ring.ArithRing.
From Coq Require Import setoid_ring.Ncring_tac.
From Coq Require Import setoid_ring.Ring_theory.
From Coq Require Import setoid_ring.InitialRing.
From Coq Require Import setoid_ring.Ring.
From Coq Require Import setoid_ring.Ring_base.
From Coq Require Import setoid_ring.Ring_tac.
From Coq Require Import setoid_ring.BinList.
From Coq Require Import setoid_ring.ZArithRing.
From Coq Require Import setoid_ring.RealField.
From Coq Require Import setoid_ring.Rings_R.
From Coq Require Import setoid_ring.Field_theory.
From Coq Require Import funind.Recdef.
From Coq Require Import funind.FunInd.
From Coq Require Import ZArith.Zabs.
From Coq Require Import ZArith.Znumtheory.
From Coq Require Import ZArith.Int.
From Coq Require Import ZArith.Zmin.
From Coq Require Import ZArith.Zpow_def.
From Coq Require Import ZArith.Wf_Z.
From Coq Require Import ZArith.BinIntDef.
From Coq Require Import ZArith.Zbool.
From Coq Require Import ZArith.Zminmax.
From Coq Require Import ZArith.Znat.
From Coq Require Import ZArith.Zhints.
From Coq Require Import ZArith.Zeuclid.
From Coq Require Import ZArith.ZArith_dec.
From Coq Require Import ZArith.Zquot.
From Coq Require Import ZArith.Zmax.
From Coq Require Import ZArith.Zcomplements.
From Coq Require Import ZArith.Zwf.
From Coq Require Import ZArith.Zeven.
From Coq Require Import ZArith.ZArith_base.
From Coq Require Import ZArith.Zmisc.
From Coq Require Import ZArith.BinInt.
From Coq Require Import ZArith.Zpower.
From Coq Require Import ZArith.Zbitwise.
From Coq Require Import ZArith.ZArith.
From Coq Require Import ZArith.Zcompare.
From Coq Require Import ZArith.Zpow_alt.
From Coq Require Import ZArith.Zorder.
From Coq Require Import ZArith.Zdiv.
From Coq Require Import ZArith.auxiliary.
From Coq Require Import ZArith.Zgcd_alt.
From Coq Require Import ZArith.Zpow_facts.

From Lemmas Require Import Loader.
 Createdb.