From CoqEAL Require Import theory.smith.
From CoqEAL Require Import theory.polydvd.
From CoqEAL Require Import theory.dvdring.
From CoqEAL Require Import theory.atomic_operations.
From CoqEAL Require Import theory.frobenius_form.
From CoqEAL Require Import theory.kaplansky.
From CoqEAL Require Import theory.companion.
From CoqEAL Require Import theory.bareiss_dvdring.
From CoqEAL Require Import theory.rank.
From CoqEAL Require Import theory.edr.
From CoqEAL Require Import theory.gauss.
From CoqEAL Require Import theory.smith_complements.
From CoqEAL Require Import theory.ssrcomplements.
From CoqEAL Require Import theory.stronglydiscrete.
From CoqEAL Require Import theory.perm_eq_image.
From CoqEAL Require Import theory.bareiss.
From CoqEAL Require Import theory.ssralg_ring_tac.
From CoqEAL Require Import theory.binetcauchy.
From CoqEAL Require Import theory.minor.
From CoqEAL Require Import theory.jordan.
From CoqEAL Require Import theory.smithpid.
From CoqEAL Require Import theory.toomcook.
From CoqEAL Require Import theory.similar.
From CoqEAL Require Import theory.coherent.
From CoqEAL Require Import theory.strassen.
From CoqEAL Require Import theory.closed_poly.
From CoqEAL Require Import theory.mxstructure.
From CoqEAL Require Import theory.karatsuba.
From CoqEAL Require Import theory.fpmod.
From CoqEAL Require Import refinements.poly_op.
From CoqEAL Require Import refinements.seqmx.
From CoqEAL Require Import refinements.bareiss_eff.
From CoqEAL Require Import refinements.seqmx_complements.
From CoqEAL Require Import refinements.hpoly.
From CoqEAL Require Import refinements.boolF2.
From CoqEAL Require Import refinements.seqpoly.
From CoqEAL Require Import refinements.param.
From CoqEAL Require Import refinements.rational.
From CoqEAL Require Import refinements.binnat.
From CoqEAL Require Import refinements.poly_div.
From CoqEAL Require Import refinements.binord.
From CoqEAL Require Import refinements.hrel.
From CoqEAL Require Import refinements.binint.
From CoqEAL Require Import refinements.trivial_seq.
From CoqEAL Require Import refinements.refinements.
From CoqEAL Require Import refinements.pos.
From CoqEAL Require Import refinements.binrat.
From CoqEAL Require Import refinements.karatsuba.
From CoqEAL Require Import refinements.multipoly.
From CoqEAL Require Import refinements.examples.irred.

From Lemmas Require Import Loader.
 Createdb.