From MathClasses Require Import varieties.rings.
From MathClasses Require Import varieties.groups.
From MathClasses Require Import varieties.semirings.
From MathClasses Require Import varieties.semigroups.
From MathClasses Require Import varieties.empty.
From MathClasses Require Import varieties.open_terms.
From MathClasses Require Import varieties.monoids.
From MathClasses Require Import varieties.setoids.
From MathClasses Require Import varieties.abgroup.
From MathClasses Require Import varieties.closed_terms.
From MathClasses Require Import functors.constant.
From MathClasses Require Import categories.functors.
From MathClasses Require Import categories.unit.
From MathClasses Require Import categories.JMcat.
From MathClasses Require Import categories.algebras.
From MathClasses Require Import categories.empty.
From MathClasses Require Import categories.categories.
From MathClasses Require Import categories.orders.
From MathClasses Require Import categories.dual.
From MathClasses Require Import categories.setoids.
From MathClasses Require Import categories.varieties.
From MathClasses Require Import categories.product.
From MathClasses Require Import implementations.intfrac_rationals.
From MathClasses Require Import implementations.NType_naturals.
From MathClasses Require Import implementations.stdlib_rationals.
From MathClasses Require Import implementations.positive_semiring_elements.
From MathClasses Require Import implementations.bool.
From MathClasses Require Import implementations.stdlib_binary_integers.
From MathClasses Require Import implementations.nonzero_field_elements.
From MathClasses Require Import implementations.list_finite_set.
From MathClasses Require Import implementations.fast_rationals.
From MathClasses Require Import implementations.list.
From MathClasses Require Import implementations.dyadics.
From MathClasses Require Import implementations.fast_integers.
From MathClasses Require Import implementations.peano_naturals.
From MathClasses Require Import implementations.stdlib_binary_naturals.
From MathClasses Require Import implementations.ne_list.
From MathClasses Require Import implementations.option.
From MathClasses Require Import implementations.nonneg_integers_naturals.
From MathClasses Require Import implementations.field_of_fractions.
From MathClasses Require Import implementations.natpair_integers.
From MathClasses Require Import implementations.QType_rationals.
From MathClasses Require Import implementations.polynomials.
From MathClasses Require Import implementations.ZType_integers.
From MathClasses Require Import implementations.modular_ring.
From MathClasses Require Import implementations.nonneg_semiring_elements.
From MathClasses Require Import implementations.fast_naturals.
From MathClasses Require Import implementations.mset_finite_set.
From MathClasses Require Import implementations.semiring_pairs.
From MathClasses Require Import misc.JMrelation.
From MathClasses Require Import misc.propholds.
From MathClasses Require Import misc.workarounds.
From MathClasses Require Import misc.setoid_tactics.
From MathClasses Require Import misc.stdlib_hints.
From MathClasses Require Import misc.decision.
From MathClasses Require Import misc.util.
From MathClasses Require Import misc.workaround_tactics.
From MathClasses Require Import orders.rings.
From MathClasses Require Import orders.semirings.
From MathClasses Require Import orders.naturals.
From MathClasses Require Import orders.dec_fields.
From MathClasses Require Import orders.orders.
From MathClasses Require Import orders.minmax.
From MathClasses Require Import orders.lattices.
From MathClasses Require Import orders.rationals.
From MathClasses Require Import orders.nat_int.
From MathClasses Require Import orders.maps.
From MathClasses Require Import orders.integers.
From MathClasses Require Import interfaces.vectorspace.
From MathClasses Require Import interfaces.functors.
From MathClasses Require Import interfaces.canonical_names.
From MathClasses Require Import interfaces.sequences.
From MathClasses Require Import interfaces.finite_sets.
From MathClasses Require Import interfaces.additional_operations.
From MathClasses Require Import interfaces.naturals.
From MathClasses Require Import interfaces.universal_algebra.
From MathClasses Require Import interfaces.monads.
From MathClasses Require Import interfaces.orders.
From MathClasses Require Import interfaces.ua_basic.
From MathClasses Require Import interfaces.rationals.
From MathClasses Require Import interfaces.abstract_algebra.
From MathClasses Require Import interfaces.integers.
From MathClasses Require Import theory.monoid_normalization.
From MathClasses Require Import theory.ua_term_monad.
From MathClasses Require Import theory.ua_transference.
From MathClasses Require Import theory.CoqStreams.
From MathClasses Require Import theory.ua_subvariety.
From MathClasses Require Import theory.functors.
From MathClasses Require Import theory.quote_monoid.
From MathClasses Require Import theory.products.
From MathClasses Require Import theory.rings.
From MathClasses Require Import theory.ring_congruence.
From MathClasses Require Import theory.sequences.
From MathClasses Require Import theory.finite_sets.
From MathClasses Require Import theory.groups.
From MathClasses Require Import theory.int_abs.
From MathClasses Require Import theory.strong_setoids.
From MathClasses Require Import theory.ua_subalgebra.
From MathClasses Require Import theory.naturals.
From MathClasses Require Import theory.cut_minus.
From MathClasses Require Import theory.categories.
From MathClasses Require Import theory.ring_ideals.
From MathClasses Require Import theory.dec_fields.
From MathClasses Require Import theory.monads.
From MathClasses Require Import theory.int_pow.
From MathClasses Require Import theory.forget_algebra.
From MathClasses Require Import theory.ua_homomorphisms.
From MathClasses Require Import theory.adjunctions.
From MathClasses Require Import theory.forget_variety.
From MathClasses Require Import theory.int_to_nat.
From MathClasses Require Import theory.ua_subalgebraT.
From MathClasses Require Import theory.setoids.
From MathClasses Require Import theory.shiftl.
From MathClasses Require Import theory.lattices.
From MathClasses Require Import theory.ua_packed.
From MathClasses Require Import theory.ua_products.
From MathClasses Require Import theory.rationals.
From MathClasses Require Import theory.fields.
From MathClasses Require Import theory.jections.
From MathClasses Require Import theory.series.
From MathClasses Require Import theory.ua_congruence.
From MathClasses Require Import theory.nat_pow.
From MathClasses Require Import theory.abs.
From MathClasses Require Import theory.streams.
From MathClasses Require Import theory.integers.
From MathClasses Require Import theory.ua_mapped_operations.
From MathClasses Require Import theory.nat_distance.
From MathClasses Require Import quote.classquote.

From Lemmas Require Import Loader.
 Createdb.