From Mtac2 Require Import Pattern.
From Mtac2 Require Import Base.
From Mtac2 Require Import Mtac2.
From Mtac2 Require Import DecomposeApp.
From Mtac2 Require Import meta.MTeleMatch.
From Mtac2 Require Import meta.MTeleMatchDef.
From Mtac2 Require Import meta.MFix.
From Mtac2 Require Import meta.MFixDef.
From Mtac2 Require Import meta.Exhaustive.
From Mtac2 Require Import lib.Datatypes.
From Mtac2 Require Import lib.Utils.
From Mtac2 Require Import lib.Specif.
From Mtac2 Require Import lib.List.
From Mtac2 Require Import lib.Logic.
From Mtac2 Require Import tactics.ImportedTactics.
From Mtac2 Require Import tactics.IntroPatt.
From Mtac2 Require Import tactics.Tactics.
From Mtac2 Require Import tactics.CompoundTactics.
From Mtac2 Require Import tactics.Ttactics.
From Mtac2 Require Import tactics.TacticsBase.
From Mtac2 Require Import tactics.ConstrSelector.
From Mtac2 Require Import ideas.DepDestruct.
From Mtac2 Require Import ideas.Abstract.
From Mtac2 Require Import ideas.SubgoalsStrict.
From Mtac2 Require Import ideas.SumRun.
From Mtac2 Require Import ideas.StaticApply.
From Mtac2 Require Import ideas.Transport.
From Mtac2 Require Import intf.DeclarationDefs.
From Mtac2 Require Import intf.Dyn.
From Mtac2 Require Import intf.Goals.
From Mtac2 Require Import intf.M.
From Mtac2 Require Import intf.Name.
From Mtac2 Require Import intf.MTele.
From Mtac2 Require Import intf.Unification.
From Mtac2 Require Import intf.Lift.
From Mtac2 Require Import intf.Reduction.
From Mtac2 Require Import intf.Case.
From Mtac2 Require Import intf.Tm_kind.
From Mtac2 Require Import intf.Sorts.
From Mtac2 Require Import intf.Exceptions.

From Lemmas Require Import Loader.
 Createdb.